name: ezycart
description: "EzyCart - A modern Flutter E-commerce Application."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.9.2

#---------------------PACKAGES--------------#
dependencies:
  flutter:
    sdk: flutter

  #Utility packages
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.0.2
  url_launcher: ^6.1.12
  carousel_slider: ^5.1.1
  flutter_native_splash: ^2.3.2
  font_awesome_flutter: ^10.7.0
  smooth_page_indicator: ^1.1.0

  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #State Management
  get: ^4.6.5
  get_storage: ^2.1.1

  #product specific
  readmore: ^3.0.0
  flutter_rating_bar: ^4.0.1

#------------------PACKAGE END --------------#
dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  #--------------LOCAL ASSETS---------------#
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/banners/
    - assets/icons/categories/
    - assets/images/animations/
    - assets/images/on_boarding_images/
    - assets/images/products/

  #------------------LOCAL FONTS-------------#
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
          weight: 400
          style: italic
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
